### ISSUE TITLE
IPython.parallel deprecated

### ISSUE THREAD

**Issue by jarthurgross** [QInfer/python-qinfer#38] opened 2016-03-04 19:44 UTC
I just updated my Anaconda 2.7 and installed qinfer, and got the following warnings:

    .../IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
      "You should import from ipyparallel instead.", ShimWarning)
    .../python-qinfer/src/qinfer/parallel.py:52: UserWarning: Could not import IPython parallel. Parallelization support will be disabled.
      "Could not import IPython parallel. "

Doesn't seem to be a big deal, but since I didn't see anything about it in the other issues I thought I'd bring it up.

**Comment by cgranade** [comment] 2016-03-04 19:52
That's a good catch, thanks! The IPython/Jupyter split a while ago left a few things broken, and I guess we didn't get the parallel support fixed.

**Comment by cgranade** [comment] 2016-04-05 01:04
With #39, I'm working on cleaning up the parallelization support by fixing bugs, and improving documentation and error messages. As a part of that, I'll kill off the old ``IPython.parallel`` import, and make it clear that this requires the new ``ipyparallel`` package. Hopefully that should address the last of the breakages caused by the IPython/Jupyter split.

**Comment by cgranade** [comment] 2016-04-08 06:00
With #39 merged in, I think that QInfer now handles the ``ipyparallel``/``IPython.parallel`` split much better, so I'll go on and close this issue for now. Thanks!

**Closed by cgranade** 2016-04-08 06:00 UTC
